import jsPDF from "jspdf";

export interface MatchReport {
  summary: string;
  strengths: string[];
  weaknesses: string[];
  technicalAnalysis: {
    dominantTechniques: string;
    sideBalance: string;
    scoringPattern: string;
    defensePattern: string;
  };
  recommendations: Array<{
    area: string;
    advice: string;
    priority: "high" | "medium" | "low";
  }>;
  trainingFocus: string[];
  tacticalNotes: string;
}

const PRIMARY: [number, number, number] = [14, 165, 233]; // #0ea5e9
const TEXT: [number, number, number] = [30, 41, 59];
const MUTED: [number, number, number] = [100, 116, 139];

function priorityColor(p: string): [number, number, number] {
  if (p === "high") return [220, 38, 38];
  if (p === "medium") return [217, 119, 6];
  return [22, 163, 74];
}

export function generateMatchReportPdf(
  report: MatchReport,
  meta: { athleteName: string; videoTitle: string; matchDate?: string }
): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  function ensureSpace(needed: number) {
    if (y + needed > pageH - 20) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  }

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      `Generated by Sportstalent.dk · ${new Date().toLocaleDateString()}`,
      margin,
      pageH - 8,
    );
  }

  function sectionTitle(text: string) {
    ensureSpace(12);
    doc.setFillColor(...PRIMARY);
    doc.rect(margin, y, contentW, 7, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(text, margin + 2, y + 5);
    y += 10;
    doc.setTextColor(...TEXT);
    doc.setFont("helvetica", "normal");
  }

  function paragraph(text: string, size = 10, indent = 0, maxW = contentW) {
    doc.setFontSize(size);
    doc.setTextColor(...TEXT);
    const lines = doc.splitTextToSize(text || "—", maxW - indent);
    for (const ln of lines) {
      ensureSpace(size * 0.5);
      doc.text(ln, margin + indent, y);
      y += size * 0.5;
    }
    y += 1;
  }

  function bulletList(items: string[]) {
    doc.setFontSize(10);
    doc.setTextColor(...TEXT);
    for (const item of items || []) {
      const lines = doc.splitTextToSize(item, contentW - 6);
      ensureSpace(lines.length * 5 + 1);
      doc.setFillColor(...PRIMARY);
      doc.circle(margin + 2, y - 1.2, 0.8, "F");
      doc.text(lines, margin + 6, y);
      y += lines.length * 5 + 1;
    }
    y += 1;
  }

  // ===== Header =====
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageW, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("SPORTSTALENT.DK", margin, 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Match Analysis Report", margin, 16);
  y = 30;

  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(meta.athleteName, margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(
    `${meta.videoTitle}${meta.matchDate ? ` · ${meta.matchDate}` : ""}`,
    margin,
    y,
  );
  y += 8;

  // ===== Summary =====
  sectionTitle("Summary");
  paragraph(report.summary);

  // ===== Strengths & Weaknesses (two columns) =====
  sectionTitle("Strengths & Weaknesses");
  const colW = (contentW - 4) / 2;
  const yStart = y;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(22, 163, 74);
  doc.text("Strengths", margin, y);
  doc.setTextColor(220, 38, 38);
  doc.text("Weaknesses", margin + colW + 4, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT);
  doc.setFontSize(9);

  const sLines = (report.strengths || []).map((s) => doc.splitTextToSize("• " + s, colW));
  const wLines = (report.weaknesses || []).map((w) => doc.splitTextToSize("• " + w, colW));
  let yS = y;
  let yW = y;
  for (const block of sLines) {
    doc.text(block, margin, yS);
    yS += block.length * 4.5 + 1;
  }
  for (const block of wLines) {
    doc.text(block, margin + colW + 4, yW);
    yW += block.length * 4.5 + 1;
  }
  y = Math.max(yS, yW) + 3;

  // ===== Technical Analysis =====
  sectionTitle("Technical Analysis");
  const ta = report.technicalAnalysis || ({} as any);
  function subSection(label: string, value: string) {
    ensureSpace(8);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PRIMARY);
    doc.text(label, margin, y);
    y += 4.5;
    doc.setFont("helvetica", "normal");
    paragraph(value, 9, 2);
  }
  subSection("Dominant Techniques", ta.dominantTechniques || "—");
  subSection("Side Balance", ta.sideBalance || "—");
  subSection("Scoring Pattern", ta.scoringPattern || "—");
  subSection("Defense Pattern", ta.defensePattern || "—");

  // ===== Recommendations table =====
  sectionTitle("Training Recommendations");
  const recs = report.recommendations || [];
  const cAreaW = 38;
  const cPriW = 22;
  const cAdvW = contentW - cAreaW - cPriW - 4;
  // header
  ensureSpace(8);
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y - 4, contentW, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT);
  doc.text("Area", margin + 1, y);
  doc.text("Advice", margin + cAreaW + 2, y);
  doc.text("Priority", margin + cAreaW + cAdvW + 4, y);
  y += 4;
  doc.setFont("helvetica", "normal");
  for (const r of recs) {
    const advLines = doc.splitTextToSize(r.advice || "—", cAdvW);
    const areaLines = doc.splitTextToSize(r.area || "—", cAreaW - 2);
    const rowH = Math.max(advLines.length, areaLines.length) * 4.2 + 3;
    ensureSpace(rowH + 2);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y - 2, margin + contentW, y - 2);
    doc.setTextColor(...TEXT);
    doc.text(areaLines, margin + 1, y + 1);
    doc.text(advLines, margin + cAreaW + 2, y + 1);
    const [pr, pg, pb] = priorityColor(r.priority);
    doc.setFillColor(pr, pg, pb);
    doc.roundedRect(margin + cAreaW + cAdvW + 4, y - 2, cPriW - 2, 5, 1, 1, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(
      (r.priority || "").toUpperCase(),
      margin + cAreaW + cAdvW + 4 + (cPriW - 2) / 2,
      y + 1.4,
      { align: "center" },
    );
    doc.setFontSize(9);
    y += rowH;
  }
  y += 2;

  // ===== Training Focus =====
  sectionTitle("Training Focus");
  bulletList(report.trainingFocus || []);

  // ===== Tactical Notes =====
  sectionTitle("Tactical Notes");
  paragraph(report.tacticalNotes || "—");

  addFooter();

  const safeName = (meta.videoTitle || "match").replace(/[^a-zA-Z0-9._-]/g, "_");
  doc.save(`match-report-${safeName}.pdf`);
}
