// AUTO-GENERATED catalog of physical tests. See user spec for structure.
// Single source of truth: every test has id, category, inputType, unit, direction,
// and per-locale name + protocol. Results are saved to physical_test_results using dbTestName.

import type { Locale } from "@/i18n/translations";

export type TestInputType = "stopwatch" | "countdown" | "level" | "distance" | "weight" | "count" | "time_hold";
export type TestDirection = "lower_is_better" | "higher_is_better";
export type TestCategory =
  | "endurance" | "speed" | "agility" | "reaction" | "muscular_endurance"
  | "power" | "strength" | "balance" | "flexibility";

export interface TestDefinition {
  id: string;
  dbTestName: string;
  category: TestCategory;
  inputType: TestInputType;
  unit: string;
  direction: TestDirection;
  countdownSeconds?: number;
  names: Record<Locale, string>;
  protocols: Record<Locale, string>;
}

export const TEST_CATEGORIES: TestCategory[] = [
  "endurance", "speed", "agility", "reaction", "muscular_endurance",
  "power", "strength", "balance", "flexibility",
];

export const TEST_CATALOG: TestDefinition[] = [
  {
    id: "cooper_12min",
    dbTestName: "Cooper Test",
    category: "endurance",
    inputType: "countdown",
    unit: "m",
    direction: "higher_is_better",
    countdownSeconds: 720,
    names: {
      en: "12-Minute Run (Cooper)",
      da: "12-minutters løb (Cooper)",
      sv: "12-minuters löpning (Cooper)",
      de: "12-Minuten-Lauf (Cooper)",
      ar: "اختبار كوبر 12 دقيقة",
      no: "12-minutters løp (Cooper)",
      es: "Test de Cooper 12 minutos",
    },
    protocols: {
      en: "Run as far as possible on a flat track in exactly 12 minutes. Record the total distance in meters at the end.",
      da: "Løb så langt som muligt på en flad bane på præcis 12 minutter. Notér den samlede distance i meter ved tidens udløb.",
      sv: "Spring så långt som möjligt på en plan bana under exakt 12 minuter. Notera total sträcka i meter vid slutet.",
      de: "Laufe in genau 12 Minuten so weit wie möglich auf flacher Strecke. Notiere die Gesamtstrecke in Metern am Ende.",
      ar: "اركض أطول مسافة ممكنة على مسار مستوٍ خلال 12 دقيقة بالضبط، وسجّل المسافة بالمتر عند انتهاء الوقت.",
      no: "Løp så langt som mulig på flat bane i nøyaktig 12 minutter. Noter total distanse i meter ved slutt.",
      es: "Corre la mayor distancia posible en pista plana durante exactamente 12 minutos. Registra la distancia total en metros.",
    },
  },
  {
    id: "shuttle_beep_20m",
    dbTestName: "Beep Test",
    category: "endurance",
    inputType: "level",
    unit: "level",
    direction: "higher_is_better",
    names: {
      en: "20m Shuttle/Beep Test",
      da: "20m Shuttle/Beep Test",
      sv: "20m Shuttle/Beep Test",
      de: "20m Shuttle/Beep Test",
      ar: "اختبار البيب 20م",
      no: "20m Shuttle/Beep Test",
      es: "Test de Course Navette / Beep 20m",
    },
    protocols: {
      en: "Run back and forth between two lines 20 m apart, matching the beep tempo which steadily increases. Record highest level/shuttle reached.",
      da: "Løb frem og tilbage mellem to linjer 20 m fra hinanden i takt med bip-lyden, som gradvist øger tempoet. Notér det højeste niveau/shuttle der nås.",
      sv: "Spring fram och tillbaka mellan två linjer 20 m isär i takt med pipet, som ökar tempot. Notera högsta nivå/shuttle.",
      de: "Laufe zwischen zwei Linien 20 m im Pieptempo, das stetig ansteigt. Notiere die höchste erreichte Stufe.",
      ar: "اركض ذهابًا وإيابًا بين خطين تفصلهما 20م حسب إيقاع الصافرة المتسارع. سجّل أعلى مستوى تم الوصول إليه.",
      no: "Løp frem og tilbake mellom to linjer 20 m fra hverandre i takt med pip-tempoet som øker. Noter høyeste nivå.",
      es: "Corre entre dos líneas separadas 20m al ritmo del pitido que aumenta progresivamente. Registra el nivel más alto alcanzado.",
    },
  },
  {
    id: "run_400m",
    dbTestName: "400m Run",
    category: "speed",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "400m Run",
      da: "400m løb",
      sv: "400m löpning",
      de: "400m Lauf",
      ar: "جري 400م",
      no: "400m løp",
      es: "Carrera de 400m",
    },
    protocols: {
      en: "Run 400 m as fast as possible on a track. Record time in seconds.",
      da: "Løb 400 m så hurtigt som muligt på en bane. Notér tiden i sekunder.",
      sv: "Spring 400 m så snabbt som möjligt. Notera tid i sekunder.",
      de: "Laufe 400 m so schnell wie möglich. Notiere die Zeit in Sekunden.",
      ar: "اركض 400م بأقصى سرعة. سجّل الزمن بالثواني.",
      no: "Løp 400 m så raskt som mulig. Noter tid i sekunder.",
      es: "Corre 400 m lo más rápido posible. Registra el tiempo en segundos.",
    },
  },
  {
    id: "queens_college_step",
    dbTestName: "Queens College Step Test",
    category: "endurance",
    inputType: "count",
    unit: "bpm",
    direction: "lower_is_better",
    names: {
      en: "Queens College Step Test",
      da: "Queens College Step Test",
      sv: "Queens College Step Test",
      de: "Queens College Step Test",
      ar: "اختبار درج كوينز كوليدج",
      no: "Queens College Step Test",
      es: "Test del escalón Queens College",
    },
    protocols: {
      en: "Step up/down on a 41 cm box for 3 min (22 steps/min women, 24 steps/min men). Measure pulse for 15 sec immediately after and enter as bpm.",
      da: "Træd op og ned på en 41 cm høj kasse i 3 min (22 trin/min kvinder, 24 trin/min mænd). Mål puls i 15 sek umiddelbart efter og indtast som bpm.",
      sv: "Stega upp/ner på 41 cm låda i 3 min (22/min kvinnor, 24/min män). Mät puls 15 sek direkt efter och ange som bpm.",
      de: "3 Min auf/ab Box 41 cm (22/min Frauen, 24/min Männer). Puls 15 Sek danach messen, als bpm eintragen.",
      ar: "اصعد وانزل صندوقًا بارتفاع 41سم لمدة 3 دقائق (22 خطوة/د للنساء، 24 للرجال). قس النبض 15 ثانية بعد الانتهاء وأدخله بالنبضات/دقيقة.",
      no: "Tråkk opp/ned på 41 cm kasse i 3 min (22/min kvinner, 24/min menn). Mål puls 15 sek etter, oppgi som bpm.",
      es: "Sube/baja un cajón de 41 cm durante 3 min (22 pasos/min mujeres, 24 hombres). Mide el pulso 15 s al terminar e introdúcelo en ppm.",
    },
  },
  {
    id: "harvard_step",
    dbTestName: "Harvard Step Test",
    category: "endurance",
    inputType: "count",
    unit: "bpm",
    direction: "lower_is_better",
    names: {
      en: "Harvard Step Test",
      da: "Harvard Step Test",
      sv: "Harvard Step Test",
      de: "Harvard Step Test",
      ar: "اختبار درج هارفارد",
      no: "Harvard Step Test",
      es: "Test del escalón de Harvard",
    },
    protocols: {
      en: "Step up/down on a 50 cm box at 30 steps/min for up to 5 min. Measure recovery pulse after the test and enter as bpm.",
      da: "Træd op og ned på en 50 cm kasse i 30 trin/min i op til 5 min. Mål puls i hvile efter testen og indtast som bpm.",
      sv: "Stega upp/ner på 50 cm låda, 30/min, upp till 5 min. Mät återhämtningspuls efter testet, ange som bpm.",
      de: "5 Min auf/ab 50 cm Box, 30/min. Puls nach Test messen, als bpm eintragen.",
      ar: "اصعد وانزل صندوقًا 50سم بمعدل 30/د حتى 5 دقائق. قس نبض التعافي بعد الاختبار وأدخله بـ bpm.",
      no: "Tråkk opp/ned 50 cm kasse, 30/min, inntil 5 min. Mål restitusjonspuls etterpå, oppgi som bpm.",
      es: "Sube/baja cajón 50 cm a 30 pasos/min hasta 5 min. Mide el pulso de recuperación al terminar e introdúcelo en ppm.",
    },
  },
  {
    id: "run_1_6km",
    dbTestName: "1.6 km Run",
    category: "endurance",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "1.6 km Run",
      da: "1,6 km løb",
      sv: "1,6 km löpning",
      de: "1,6 km Lauf",
      ar: "جري 1.6 كم",
      no: "1,6 km løp",
      es: "Carrera de 1,6 km",
    },
    protocols: {
      en: "Run 1.6 km as fast as possible on a flat course. Record time in seconds.",
      da: "Løb 1,6 km så hurtigt som muligt på flad strækning. Notér tiden i sekunder.",
      sv: "Spring 1,6 km så snabbt som möjligt. Notera tid i sekunder.",
      de: "Laufe 1,6 km so schnell wie möglich. Zeit in Sekunden notieren.",
      ar: "اركض 1.6 كم بأقصى سرعة. سجّل الزمن بالثواني.",
      no: "Løp 1,6 km så raskt som mulig. Noter tid i sekunder.",
      es: "Corre 1,6 km lo más rápido posible. Registra el tiempo en segundos.",
    },
  },
  {
    id: "run_1_mile",
    dbTestName: "1 Mile Run",
    category: "endurance",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "1 Mile Run",
      da: "1 mile løb",
      sv: "1 mile löpning",
      de: "1-Meilen-Lauf",
      ar: "جري ميل واحد",
      no: "1 mile løp",
      es: "Carrera de 1 milla",
    },
    protocols: {
      en: "Run 1 mile (1609 m) as fast as possible. Record time in seconds.",
      da: "Løb 1 engelsk mil (1609 m) så hurtigt som muligt. Notér tiden i sekunder.",
      sv: "Spring 1 mile (1609 m) så snabbt som möjligt. Notera tid i sekunder.",
      de: "Laufe 1 Meile (1609 m) so schnell wie möglich. Zeit in Sekunden notieren.",
      ar: "اركض ميلًا واحدًا (1609م) بأقصى سرعة. سجّل الزمن بالثواني.",
      no: "Løp 1 mile (1609 m) så raskt som mulig. Noter tid i sekunder.",
      es: "Corre 1 milla (1609 m) lo más rápido posible. Registra el tiempo en segundos.",
    },
  },
  {
    id: "yoyo_endurance",
    dbTestName: "Yo-Yo Endurance Test",
    category: "endurance",
    inputType: "level",
    unit: "niveau",
    direction: "higher_is_better",
    names: {
      en: "Yo-Yo Endurance Test",
      da: "Yo-Yo udholdenhedstest",
      sv: "Yo-Yo uthållighetstest",
      de: "Yo-Yo Ausdauertest",
      ar: "اختبار يويو للتحمل",
      no: "Yo-Yo utholdenhetstest",
      es: "Test de Yo-Yo de resistencia",
    },
    protocols: {
      en: "Run 2×20 m shuttles to the beep, which accelerates. Record highest level (or meters) reached before failure.",
      da: "Løb 2×20 m shuttle i takt med bip, som accelererer. Notér det højeste niveau (eller meter) der nås før udmatning.",
      sv: "Spring 2×20 m shuttle i takt med pipet som ökar. Notera högsta nivå nådd.",
      de: "Laufe 2×20 m Shuttle zum Pieptempo. Höchste erreichte Stufe notieren.",
      ar: "اركض 2×20م شاتل وفق الصافرة المتسارعة. سجّل أعلى مستوى تم بلوغه.",
      no: "Løp 2×20 m shuttle i pip-tempo. Noter høyeste nivå.",
      es: "Corre lanzaderas 2×20 m al ritmo del pitido. Registra el nivel más alto alcanzado.",
    },
  },
  {
    id: "sprint_50m",
    dbTestName: "50m Sprint",
    category: "speed",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "50m Sprint",
      da: "50m sprint",
      sv: "50m sprint",
      de: "50m Sprint",
      ar: "عدو 50م",
      no: "50m sprint",
      es: "Sprint 50m",
    },
    protocols: {
      en: "Sprint 50 m in a straight line from a standing start. Record time in seconds.",
      da: "Sprint 50 m i lige linje fra stående start. Notér tiden i sekunder.",
      sv: "Sprinta 50 m i rak linje från stående start. Tid i sekunder.",
      de: "Sprinte 50 m gerade aus dem Stand. Zeit in Sekunden notieren.",
      ar: "اعدُ 50م في خط مستقيم من البدء واقفًا. سجّل الزمن بالثواني.",
      no: "Sprint 50 m i rett linje fra stående start. Tid i sekunder.",
      es: "Sprint de 50 m en línea recta desde parado. Registra el tiempo en segundos.",
    },
  },
  {
    id: "sprint_35m",
    dbTestName: "35m Sprint",
    category: "speed",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "35m Sprint",
      da: "35m sprint",
      sv: "35m sprint",
      de: "35m Sprint",
      ar: "عدو 35م",
      no: "35m sprint",
      es: "Sprint 35m",
    },
    protocols: {
      en: "Sprint 35 m from a standing start. Record time in seconds.",
      da: "Sprint 35 m fra stående start. Notér tiden i sekunder.",
      sv: "Sprinta 35 m från stående start. Tid i sekunder.",
      de: "Sprinte 35 m aus dem Stand. Zeit in Sekunden notieren.",
      ar: "اعدُ 35م من بدء واقف. سجّل الزمن بالثواني.",
      no: "Sprint 35 m fra stående start. Tid i sekunder.",
      es: "Sprint de 35 m desde parado. Registra el tiempo en segundos.",
    },
  },
  {
    id: "run_300m",
    dbTestName: "300m Run",
    category: "speed",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "300m Run",
      da: "300m løb",
      sv: "300m löpning",
      de: "300m Lauf",
      ar: "جري 300م",
      no: "300m løp",
      es: "Carrera de 300m",
    },
    protocols: {
      en: "Run 300 m as fast as possible. Record time in seconds.",
      da: "Løb 300 m så hurtigt som muligt. Notér tiden i sekunder.",
      sv: "Spring 300 m så snabbt som möjligt. Tid i sekunder.",
      de: "Laufe 300 m so schnell wie möglich. Zeit in Sekunden notieren.",
      ar: "اركض 300م بأقصى سرعة. سجّل الزمن بالثواني.",
      no: "Løp 300 m så raskt som mulig. Tid i sekunder.",
      es: "Corre 300 m lo más rápido posible. Registra el tiempo en segundos.",
    },
  },
  {
    id: "illinois_agility",
    dbTestName: "Illinois Agility Test",
    category: "agility",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "Illinois Agility Test",
      da: "Illinois Agility Test",
      sv: "Illinois Agility Test",
      de: "Illinois Agility Test",
      ar: "اختبار رشاقة إلينوي",
      no: "Illinois Agility Test",
      es: "Test de Agilidad Illinois",
    },
    protocols: {
      en: "Complete the Illinois course (10×5 m with slalom around 4 cones) as fast as possible. Record time in seconds.",
      da: "Gennemfør Illinois-banen (10×5 m med slalom om 4 kegler) så hurtigt som muligt. Notér tiden i sekunder.",
      sv: "Genomför Illinois-banan (10×5 m med slalom runt 4 koner) så snabbt som möjligt. Tid i sekunder.",
      de: "Absolviere den Illinois-Parcours (10×5 m mit Slalom um 4 Kegel) so schnell wie möglich. Zeit in Sekunden notieren.",
      ar: "أكمل مسار إلينوي (10×5م مع تعرّج حول 4 شواخص) بأسرع وقت. سجّل الزمن بالثواني.",
      no: "Gjennomfør Illinois-løypa (10×5 m med slalåm rundt 4 kjegler) så raskt som mulig. Tid i sekunder.",
      es: "Completa el circuito Illinois (10×5 m con slalom alrededor de 4 conos) lo más rápido posible. Tiempo en segundos.",
    },
  },
  {
    id: "semo_agility",
    dbTestName: "Semo Agility Test",
    category: "agility",
    inputType: "stopwatch",
    unit: "sek",
    direction: "lower_is_better",
    names: {
      en: "Semo Agility Test",
      da: "Semo Agility Test",
      sv: "Semo Agility Test",
      de: "Semo Agility Test",
      ar: "اختبار رشاقة سيمو",
      no: "Semo Agility Test",
      es: "Test de Agilidad Semo",
    },
    protocols: {
      en: "Complete the Semo course (6×4 m rectangle with side-step, backwards and sprint) as fast as possible. Record time in seconds.",
      da: "Gennemfør Semo-banen (rektangel 6×4 m med sideløb, baglæns og sprint) så hurtigt som muligt. Notér tiden i sekunder.",
      sv: "Genomför Semo-banan (6×4 m rektangel med sidsteg, baklänges och sprint) snabbast möjligt. Tid i sekunder.",
      de: "Absolviere den Semo-Parcours (6×4 m mit Seitwärts, Rückwärts und Sprint) so schnell wie möglich. Zeit in Sekunden.",
      ar: "أكمل مسار سيمو (مستطيل 6×4م مع خطوة جانبية وللخلف وعدو) بأسرع وقت. سجّل الزمن بالثواني.",
      no: "Gjennomfør Semo-løypa (6×4 m rektangel med sidesteg, bakover, sprint) så raskt som mulig. Tid i sekunder.",
      es: "Completa el circuito Semo (rectángulo 6×4 m con desplazamiento lateral, hacia atrás y sprint) lo antes posible. Tiempo en segundos.",
    },
  },
  {
    id: "ruler_drop",
    dbTestName: "Ruler Drop Test",
    category: "reaction",
    inputType: "distance",
    unit: "cm",
    direction: "lower_is_better",
    names: {
      en: "Ruler Drop Test",
      da: "Ruler Drop Test",
      sv: "Lineal-droppstest",
      de: "Lineal-Falltest",
      ar: "اختبار سقوط المسطرة",
      no: "Linjal-fallstest",
      es: "Test de caída de la regla",
    },
    protocols: {
      en: "A partner holds a 30 cm ruler vertically above the athlete's open hand. Without warning, the ruler is released and caught as fast as possible. Record cm at the top of the thumb.",
      da: "En partner holder en 30 cm lineal lodret over atletens åbne hånd. Når linealen slippes uden varsel, gribes den så hurtigt som muligt. Notér antal cm målt ved tommelfingerens øverste kant.",
      sv: "En partner håller en 30 cm linjal lodrätt över atletens hand. Linjalen släpps utan förvarning och fångas snabbast möjligt. Notera cm vid tummens överkant.",
      de: "Partner hält ein 30 cm Lineal senkrecht über die offene Hand. Ohne Vorwarnung loslassen, so schnell wie möglich fangen. cm an Daumenoberkante notieren.",
      ar: "يمسك شريك مسطرة 30سم عموديًا فوق يد اللاعب. تُفلت دون إنذار وتُمسك بأسرع وقت. سجّل الـسم عند أعلى الإبهام.",
      no: "En partner holder en 30 cm linjal loddrett over åpen hånd. Slippes uten varsel og fanges raskest mulig. Noter cm ved tommelens topp.",
      es: "Un compañero sostiene una regla de 30 cm sobre la mano abierta. La suelta sin avisar y el atleta la atrapa lo más rápido posible. Registra los cm en el borde superior del pulgar.",
    },
  },
  {
    id: "wall_toss",
    dbTestName: "Wall Toss Test",
    category: "reaction",
    inputType: "count",
    unit: "antal",
    direction: "higher_is_better",
    names: {
      en: "Wall Toss Test",
      da: "Wall Toss Test",
      sv: "Wall Toss Test",
      de: "Wandwurftest",
      ar: "اختبار رمي الجدار",
      no: "Wall Toss Test",
      es: "Test de lanzamiento a la pared",
    },
    protocols: {
      en: "Stand 2 m from a wall. Throw a tennis ball with one hand, catch with the other for 30 sec. Record successful catches.",
      da: "Stå 2 m fra en væg. Kast en tennisbold mod væggen med én hånd og grib med den anden i 30 sek. Notér antal vellykkede gribninger.",
      sv: "Stå 2 m från vägg. Kasta tennisboll med ena handen, fånga med andra i 30 sek. Notera lyckade fångster.",
      de: "Stehe 2 m vor Wand. Tennisball mit einer Hand werfen, mit der anderen fangen, 30 Sek. Erfolgreiche Fänge notieren.",
      ar: "قف 2م من الجدار. ارمِ كرة تنس بيد والتقطها بالأخرى لمدة 30 ثانية. سجّل عدد الالتقاطات الناجحة.",
      no: "Stå 2 m fra vegg. Kast tennisball med én hånd, ta imot med andre i 30 sek. Noter vellykkede grep.",
      es: "Sitúate a 2 m de la pared. Lanza una pelota con una mano y atrápala con la otra durante 30 s. Registra los agarres exitosos.",
    },
  },
  {
    id: "pushup_30s",
    dbTestName: "30s Push-up Test",
    category: "muscular_endurance",
    inputType: "countdown",
    unit: "antal",
    direction: "higher_is_better",
    countdownSeconds: 30,
    names: {
      en: "30s Push-up Test",
      da: "30-sek Push-up Test",
      sv: "30-sek armhävningar",
      de: "30-Sek Liegestütze",
      ar: "اختبار الضغط 30 ثانية",
      no: "30-sek push-up test",
      es: "Test de flexiones 30s",
    },
    protocols: {
      en: "Perform as many proper push-ups as possible in 30 sec (chest to floor, full extension). Count reps.",
      da: "Lav så mange korrekte push-ups som muligt på 30 sek (bryst rører gulvet, fuld armstrækning). Tæl antal.",
      sv: "Gör så många korrekta armhävningar som möjligt på 30 sek. Räkna reps.",
      de: "So viele korrekte Liegestütze wie möglich in 30 Sek. Wiederholungen zählen.",
      ar: "نفّذ أكبر عدد من تمارين الضغط الصحيحة خلال 30 ثانية. عدّ التكرارات.",
      no: "Gjør så mange korrekte push-ups som mulig på 30 sek. Tell repetisjoner.",
      es: "Realiza el mayor número de flexiones correctas en 30 s. Cuenta las repeticiones.",
    },
  },
  {
    id: "situp_60s",
    dbTestName: "Sit-up Test",
    category: "muscular_endurance",
    inputType: "countdown",
    unit: "antal",
    direction: "higher_is_better",
    countdownSeconds: 60,
    names: {
      en: "Sit-up Test",
      da: "Sit-up Test",
      sv: "Sit-up test",
      de: "Sit-up Test",
      ar: "اختبار البطن",
      no: "Sit-up test",
      es: "Test de abdominales",
    },
    protocols: {
      en: "Perform as many proper sit-ups as possible in 60 sec. Count reps.",
      da: "Lav så mange korrekte sit-ups som muligt på 60 sek. Tæl antal.",
      sv: "Gör så många korrekta sit-ups som möjligt på 60 sek. Räkna reps.",
      de: "So viele korrekte Sit-ups wie möglich in 60 Sek. Wiederholungen zählen.",
      ar: "نفّذ أكبر عدد من تمارين البطن الصحيحة خلال 60 ثانية. عدّ التكرارات.",
      no: "Gjør så mange korrekte sit-ups som mulig på 60 sek. Tell repetisjoner.",
      es: "Realiza el mayor número de abdominales correctos en 60 s. Cuenta las repeticiones.",
    },
  },
  {
    id: "squats_60s",
    dbTestName: "Squats Test",
    category: "muscular_endurance",
    inputType: "countdown",
    unit: "antal",
    direction: "higher_is_better",
    countdownSeconds: 60,
    names: {
      en: "Squats Test",
      da: "Squats Test",
      sv: "Knäböj test",
      de: "Kniebeugen-Test",
      ar: "اختبار القرفصاء",
      no: "Knebøy-test",
      es: "Test de sentadillas",
    },
    protocols: {
      en: "Perform as many proper squats (thighs parallel to floor) as possible in 60 sec. Count reps.",
      da: "Lav så mange korrekte knæbøjninger (lårene parallelle med gulvet) som muligt på 60 sek. Tæl antal.",
      sv: "Gör så många korrekta knäböj som möjligt på 60 sek. Räkna reps.",
      de: "So viele korrekte Kniebeugen wie möglich in 60 Sek. Wiederholungen zählen.",
      ar: "نفّذ أكبر عدد من تمارين القرفصاء الصحيحة خلال 60 ثانية. عدّ التكرارات.",
      no: "Gjør så mange korrekte knebøy som mulig på 60 sek. Tell repetisjoner.",
      es: "Realiza el mayor número de sentadillas correctas en 60 s. Cuenta las repeticiones.",
    },
  },
  {
    id: "abdominal_7stage",
    dbTestName: "7-Stage Abdominal Test",
    category: "muscular_endurance",
    inputType: "level",
    unit: "niveau",
    direction: "higher_is_better",
    names: {
      en: "7-Stage Abdominal Test",
      da: "7-trins abdominaltest",
      sv: "7-stegs bukmuskeltest",
      de: "7-Stufen Bauchtest",
      ar: "اختبار البطن 7 مراحل",
      no: "7-trinns mage-test",
      es: "Test abdominal de 7 niveles",
    },
    protocols: {
      en: "Complete the 7 abdominal stages with increasing difficulty (from basic crunches to weighted V-sit). Record highest stage completed properly.",
      da: "Gennemfør de 7 niveauer af abdominaltest med stigende sværhedsgrad (fra simple crunches til V-sit med vægt). Notér højeste niveau gennemført korrekt.",
      sv: "Genomför de 7 nivåerna i stigande svårighet. Notera högsta korrekt klarade nivå.",
      de: "Absolviere die 7 Stufen mit steigender Schwierigkeit. Höchste korrekt absolvierte Stufe notieren.",
      ar: "أكمل المراحل السبع بصعوبة متزايدة. سجّل أعلى مرحلة أُديت بشكل صحيح.",
      no: "Gjennomfør de 7 nivåene med økende vanskelighet. Noter høyeste fullførte nivå.",
      es: "Completa los 7 niveles de dificultad creciente. Registra el nivel más alto completado correctamente.",
    },
  },
  {
    id: "vertical_jump",
    dbTestName: "Vertical Jump",
    category: "power",
    inputType: "distance",
    unit: "cm",
    direction: "higher_is_better",
    names: {
      en: "Vertical Jump",
      da: "Vertikalt hop",
      sv: "Vertikalhopp",
      de: "Vertikalsprung",
      ar: "القفز العمودي",
      no: "Vertikalhopp",
      es: "Salto vertical",
    },
    protocols: {
      en: "Stand sideways to a wall, mark standing reach. Jump as high as possible and mark peak. Record difference in cm.",
      da: "Stå med siden mod væggen og marker stående rækkehøjde. Hop så højt som muligt og marker top. Notér forskellen i cm.",
      sv: "Markera stående räckhöjd vid vägg. Hoppa max och markera topp. Notera differens i cm.",
      de: "Stehe seitlich an Wand, markiere Reichhöhe. Maximal hochspringen, Spitze markieren. Differenz in cm notieren.",
      ar: "قف جانبيًا بجوار جدار وحدّد ارتفاع الوصول. اقفز بأقصى ارتفاع وحدّد القمة. سجّل الفارق بالسم.",
      no: "Stå sidelengs ved vegg, marker rekkhøyde. Hopp maks, marker topp. Noter differansen i cm.",
      es: "Sitúate de lado a una pared y marca tu altura de alcance. Salta lo más alto posible y marca el pico. Registra la diferencia en cm.",
    },
  },
  {
    id: "standing_long_jump",
    dbTestName: "Standing Long Jump",
    category: "power",
    inputType: "distance",
    unit: "cm",
    direction: "higher_is_better",
    names: {
      en: "Standing Long Jump",
      da: "Stående længdespring",
      sv: "Stående längdhopp",
      de: "Standweitsprung",
      ar: "الوثب الطويل من الثبات",
      no: "Stående lengdehopp",
      es: "Salto de longitud sin impulso",
    },
    protocols: {
      en: "Toes behind start line. Two-footed jump forward as far as possible. Measure from start line to nearest heel landing in cm.",
      da: "Stå med tæerne bag startlinjen. Hop fremad med samlede ben så langt som muligt. Mål fra startlinje til nærmeste hælnedslag i cm.",
      sv: "Tår bakom startlinje. Tvåfots hopp framåt så långt som möjligt. Mät från startlinje till närmaste häl i cm.",
      de: "Zehen hinter Linie. Beidbeinig so weit wie möglich springen. Von Linie zum nächsten Ferseneindruck in cm messen.",
      ar: "الأصابع خلف خط البدء. اقفز بكلتا القدمين أبعد مسافة ممكنة. قس من الخط حتى أقرب نقطة كعب بالسم.",
      no: "Tær bak startstrek. Tofotshopp framover så langt som mulig. Mål fra strek til nærmeste hælnedslag i cm.",
      es: "Pies tras la línea. Salto a pies juntos lo más lejos posible. Mide de la línea al talón más cercano en cm.",
    },
  },
  {
    id: "seated_basket_throw",
    dbTestName: "Seated Basketball Throw",
    category: "power",
    inputType: "distance",
    unit: "m",
    direction: "higher_is_better",
    names: {
      en: "Seated Basketball Throw",
      da: "Siddende basketkast",
      sv: "Sittande basketkast",
      de: "Sitzender Basketballstoß",
      ar: "رمي كرة السلة من الجلوس",
      no: "Sittende basketballkast",
      es: "Lanzamiento de balón sentado",
    },
    protocols: {
      en: "Sit with back against a wall. Throw a basketball as far as possible with both hands from the chest. Record distance in meters.",
      da: "Sid med ryggen mod væggen. Kast en basketball så langt som muligt med to hænder fra brystet. Mål kastlængde i meter.",
      sv: "Sitt med ryggen mot vägg. Kasta basket med båda händer från bröstet så långt som möjligt. Notera meter.",
      de: "Sitze, Rücken an Wand. Basketball mit beiden Händen vom Brust so weit wie möglich werfen. Meter notieren.",
      ar: "اجلس وظهرك للجدار. ارمِ كرة السلة بكلتا اليدين من الصدر لأبعد مسافة. سجّل المسافة بالمتر.",
      no: "Sitt med rygg mot vegg. Kast basketball med begge hender fra brystet så langt som mulig. Noter meter.",
      es: "Sentado con la espalda en la pared. Lanza un balón con ambas manos desde el pecho lo más lejos posible. Registra los metros.",
    },
  },
  {
    id: "bench_1rm",
    dbTestName: "1RM Bench Press",
    category: "strength",
    inputType: "weight",
    unit: "kg",
    direction: "higher_is_better",
    names: {
      en: "1RM Bench Press",
      da: "1RM bænkpres",
      sv: "1RM bänkpress",
      de: "1RM Bankdrücken",
      ar: "1RM ضغط البنش",
      no: "1RM benkpress",
      es: "1RM press de banca",
    },
    protocols: {
      en: "Find the maximum weight you can bench-press correctly for one rep after warm-up. Record in kg.",
      da: "Find den maksimale vægt du kan løfte korrekt én gang i bænkpres efter opvarmning. Notér vægten i kg.",
      sv: "Hitta max vikt i bänkpress för 1 rep efter uppvärmning. Notera kg.",
      de: "Maximales Gewicht für 1 Wdh Bankdrücken nach Aufwärmen. In kg notieren.",
      ar: "اعثر على أعلى وزن يمكنك رفعه مرة واحدة بشكل صحيح في ضغط البنش بعد الإحماء. سجّل بالكغ.",
      no: "Finn maks vekt i benkpress for 1 rep etter oppvarming. Noter i kg.",
      es: "Encuentra el peso máximo para una repetición correcta en press de banca tras calentar. Registra en kg.",
    },
  },
  {
    id: "legpress_1rm",
    dbTestName: "1RM Leg Press",
    category: "strength",
    inputType: "weight",
    unit: "kg",
    direction: "higher_is_better",
    names: {
      en: "1RM Leg Press",
      da: "1RM benpres",
      sv: "1RM benpress",
      de: "1RM Beinpresse",
      ar: "1RM ضغط الأرجل",
      no: "1RM benpress",
      es: "1RM prensa de piernas",
    },
    protocols: {
      en: "Find the maximum weight you can leg-press correctly for one rep after warm-up. Record in kg.",
      da: "Find den maksimale vægt du kan løfte korrekt én gang i benpres efter opvarmning. Notér vægten i kg.",
      sv: "Hitta max vikt i benpress för 1 rep. Notera kg.",
      de: "Maximales Gewicht für 1 Wdh Beinpresse. In kg notieren.",
      ar: "اعثر على أعلى وزن يمكنك رفعه مرة واحدة في ضغط الأرجل. سجّل بالكغ.",
      no: "Finn maks vekt i benpress for 1 rep. Noter i kg.",
      es: "Encuentra el peso máximo para una repetición correcta en prensa de piernas. Registra en kg.",
    },
  },
  {
    id: "handgrip",
    dbTestName: "Hand Grip (Dynamometer)",
    category: "strength",
    inputType: "weight",
    unit: "kg",
    direction: "higher_is_better",
    names: {
      en: "Hand Grip (Dynamometer)",
      da: "Håndgreb (dynamometer)",
      sv: "Handgrepp (dynamometer)",
      de: "Handkraft (Dynamometer)",
      ar: "قوة القبضة (دينامومتر)",
      no: "Håndgrep (dynamometer)",
      es: "Fuerza de prensión (dinamómetro)",
    },
    protocols: {
      en: "Squeeze the dynamometer with maximum force for 3-5 sec, dominant hand, arm at side. Record best attempt in kg.",
      da: "Klem dynamometeret med maksimal kraft i 3-5 sek med dominant hånd, arm strakt ned ad siden. Notér bedste forsøg i kg.",
      sv: "Pressa dynamometern maximalt 3-5 sek med dominant hand. Bästa försök i kg.",
      de: "Dynamometer max. 3-5 Sek mit dominanter Hand drücken. Bestes Ergebnis in kg.",
      ar: "اضغط الدينامومتر بأقصى قوة 3-5 ثوانٍ باليد المهيمنة. سجّل أفضل محاولة بالكغ.",
      no: "Klem dynamometeret maks 3-5 sek med dominant hånd. Beste forsøk i kg.",
      es: "Aprieta el dinamómetro al máximo 3-5 s con la mano dominante. Registra el mejor intento en kg.",
    },
  },
  {
    id: "stork_balance",
    dbTestName: "Stork Balance Test",
    category: "balance",
    inputType: "time_hold",
    unit: "sek",
    direction: "higher_is_better",
    names: {
      en: "Stork Balance Test",
      da: "Stork Balance Test",
      sv: "Stork-balanstest",
      de: "Storch-Balancetest",
      ar: "اختبار توازن اللقلق",
      no: "Stork-balansetest",
      es: "Test del flamenco (equilibrio)",
    },
    protocols: {
      en: "Stand on dominant foot, other foot at knee, hands on hips. Lift heel and hold balance as long as possible. Record seconds.",
      da: "Stå på dominant fod, anden fod mod knæet, hænder i siden. Løft hælen og hold balancen så længe som muligt. Notér tiden i sekunder.",
      sv: "Stå på dominant fot, andra mot knät, händer i sidan. Lyft häl och håll balans så länge som möjligt. Tid i sek.",
      de: "Auf dominantem Fuß stehen, anderer Fuß am Knie, Hände an Hüften. Ferse anheben, so lange wie möglich balancieren. Sek notieren.",
      ar: "قف على القدم المهيمنة، الأخرى عند الركبة، اليدان على الورك. ارفع الكعب وحافظ على التوازن أطول مدة. سجّل بالثواني.",
      no: "Stå på dominant fot, andre mot kne, hender i siden. Løft hælen og hold balansen lengst mulig. Sek.",
      es: "De pie sobre el pie dominante, el otro en la rodilla, manos en cadera. Eleva el talón y mantén el equilibrio lo más posible. Segundos.",
    },
  },
  {
    id: "y_balance",
    dbTestName: "Y-Balance Test",
    category: "balance",
    inputType: "distance",
    unit: "cm",
    direction: "higher_is_better",
    names: {
      en: "Y-Balance Test",
      da: "Y-Balance Test",
      sv: "Y-balanstest",
      de: "Y-Balance-Test",
      ar: "اختبار توازن Y",
      no: "Y-balansetest",
      es: "Test de equilibrio en Y",
    },
    protocols: {
      en: "Stand on one leg at the Y center. Reach with free leg as far as possible in three directions (anterior, posteromedial, posterolateral). Record average reach in cm.",
      da: "Stå på ét ben i centrum af Y'et. Stræk frit ben så langt som muligt i de tre retninger (forrest, posteromedialt, posterolateralt). Notér gennemsnitlig rækkevidde i cm.",
      sv: "Stå på ett ben i Y:ets mitt. Sträck friben i tre riktningar så långt som möjligt. Notera medel-räckhöjd i cm.",
      de: "Auf einem Bein in Y-Mitte. Freies Bein in drei Richtungen so weit wie möglich strecken. Mittlere Reichweite in cm.",
      ar: "قف على ساق واحدة في مركز Y. مدّ الساق الحرة بأقصى ما يمكن في الاتجاهات الثلاثة. سجّل متوسط المدى بالسم.",
      no: "Stå på ett bein i Y-senter. Strekk fritt bein i tre retninger så langt som mulig. Noter snitt-rekkevidde i cm.",
      es: "De pie sobre una pierna en el centro de la Y. Alcanza con la otra pierna lo más lejos posible en las tres direcciones. Registra el alcance medio en cm.",
    },
  },
  {
    id: "sit_and_reach",
    dbTestName: "Sit & Reach Test",
    category: "flexibility",
    inputType: "distance",
    unit: "cm",
    direction: "higher_is_better",
    names: {
      en: "Sit & Reach Test",
      da: "Sit & Reach Test",
      sv: "Sit & Reach-test",
      de: "Sit-and-Reach-Test",
      ar: "اختبار الجلوس والوصول",
      no: "Sit & Reach-test",
      es: "Test de Sit & Reach",
    },
    protocols: {
      en: "Sit with straight legs against a box. Reach forward and push the marker as far as possible with fingertips. Record cm.",
      da: "Sid med strakte ben mod en kasse. Stræk frem og skub måleren så langt som muligt med fingerspidserne. Notér længde i cm.",
      sv: "Sitt med raka ben mot låda. Sträck framåt och skjut markören så långt som möjligt. cm.",
      de: "Mit gestreckten Beinen an Box sitzen. Mit Fingerspitzen Marker so weit wie möglich schieben. cm notieren.",
      ar: "اجلس بساقين ممدودتين باتجاه الصندوق. مدّ ذراعيك وادفع المؤشر بأبعد ما يمكن بأطراف الأصابع. سجّل بالسم.",
      no: "Sitt med strake bein mot kasse. Strekk fremover og skyv markøren så langt som mulig. cm.",
      es: "Sentado con las piernas estiradas contra el cajón. Empuja el marcador con la punta de los dedos lo más lejos posible. Registra cm.",
    },
  },
  {
    id: "shoulder_elevation",
    dbTestName: "Shoulder Elevation Test",
    category: "flexibility",
    inputType: "distance",
    unit: "cm",
    direction: "higher_is_better",
    names: {
      en: "Shoulder Elevation Test",
      da: "Skulderelevationstest",
      sv: "Skulder-elevationstest",
      de: "Schulter-Elevationstest",
      ar: "اختبار رفع الكتف",
      no: "Skulderelevasjonstest",
      es: "Test de elevación de hombro",
    },
    protocols: {
      en: "Lie prone with arms straight holding a stick. Raise stick as high as possible without bending elbows. Measure floor to stick in cm.",
      da: "Lig på maven med strakte arme og hold en pind. Løft pinden så højt som muligt uden at bøje albuerne. Mål højde fra gulv til pind i cm.",
      sv: "Ligg på mage med raka armar och en pinne. Lyft pinnen så högt som möjligt utan att böja armbågar. Höjd i cm.",
      de: "Bauchlage, gestreckte Arme, Stab halten. Stab maximal anheben ohne Ellbogen zu beugen. Boden bis Stab in cm messen.",
      ar: "استلقِ على البطن وذراعاك ممدودتان تمسكان عصا. ارفع العصا بأقصى ارتفاع دون ثني المرفقين. قس من الأرض إلى العصا بالسم.",
      no: "Ligg på magen med strake armer som holder en stang. Løft stangen så høyt som mulig uten å bøye albuer. Mål gulv til stang i cm.",
      es: "Tumbado boca abajo con los brazos estirados sosteniendo una vara. Eleva la vara lo más alto posible sin doblar codos. Mide del suelo a la vara en cm.",
    },
  },
  {
    id: "trunk_rotation",
    dbTestName: "Trunk Rotation Test",
    category: "flexibility",
    inputType: "distance",
    unit: "grader",
    direction: "higher_is_better",
    names: {
      en: "Trunk Rotation Test",
      da: "Trunk Rotation Test",
      sv: "Bål-rotationstest",
      de: "Rumpfrotations-Test",
      ar: "اختبار دوران الجذع",
      no: "Truncus-rotasjonstest",
      es: "Test de rotación del tronco",
    },
    protocols: {
      en: "Stand feet shoulder-width, arms crossed over chest. Rotate trunk maximally each side and measure the angle (degrees) or reach in cm on a marked wall.",
      da: "Stå med fødderne i skulderbredde, arme i kryds over brystet. Roter overkroppen maksimalt til hver side og mål vinklen (grader) eller rækkevidde i cm på en markeret væg.",
      sv: "Stå med fötter axelbrett, armar i kors över bröst. Rotera bålen max åt varje sida och mät vinkel (grader) eller räckhöjd cm.",
      de: "Schulterbreit stehen, Arme vor Brust. Rumpf max nach jeder Seite drehen, Winkel (Grad) oder Reichweite cm messen.",
      ar: "قف، القدمان بعرض الكتفين، اليدان متقاطعتان على الصدر. أدِر الجذع بأقصى زاوية إلى كل جهة وقس الزاوية بالدرجات.",
      no: "Stå i skulderbredde, armer i kryss over brystet. Roter overkropp maks til hver side, mål vinkel (grader) eller cm.",
      es: "De pie, pies a anchura de hombros, brazos cruzados sobre el pecho. Rota el tronco al máximo a cada lado y mide el ángulo (grados) o el alcance en cm.",
    },
  },
];

// Legacy dbTestName → catalog id, so old rows display correctly.
export const LEGACY_DB_NAME_TO_ID: Record<string, string> = {
  "Beep Test": "shuttle_beep_20m",
  "Cooper Test": "cooper_12min",
};

export function findTestByDbName(name: string): TestDefinition | undefined {
  const directHit = TEST_CATALOG.find((t) => t.dbTestName === name);
  if (directHit) return directHit;
  const mappedId = LEGACY_DB_NAME_TO_ID[name];
  if (mappedId) return TEST_CATALOG.find((t) => t.id === mappedId);
  return undefined;
}

export function findTestById(id: string): TestDefinition | undefined {
  return TEST_CATALOG.find((t) => t.id === id);
}

export function localizedTestName(def: TestDefinition, locale: Locale): string {
  return def.names[locale] || def.names.en;
}

export function localizedProtocol(def: TestDefinition, locale: Locale): string {
  return def.protocols[locale] || def.protocols.en;
}

export function isImprovement(def: TestDefinition, current: number, previous: number): boolean | null {
  if (current === previous) return null;
  if (def.direction === "lower_is_better") return current < previous;
  return current > previous;
}