project_id = "zklwergsziidgyxewbkw"

[functions.generate-plan]
verify_jwt = false

[functions.get-admin-users]
verify_jwt = false

[functions.generate-nutrition-plan]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true